version: '2.4'

services:

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=utn"
      - "RABBITMQ_DEFAULT_PASS=iasc"
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672

  aerolineas:
      build:
        context: ./aerolineas
        args:
          - NODE_ENV=development
      ports:
        - 3015:3015
      environment:
        - SERVICE=aerolineas
      env_file:
        - ./aerolineas/.env
      depends_on:
        - rabbitmq
      restart: always
      command: sh -c "sleep 10 && npm start"