version: '2.4'

services:

  statebusrabbitmq:
      build:
        context: ./statebusrabbitmq
        args:
          - NODE_ENV=development
      ports:
        # AMQP protocol port
        # - 5673:5673
        # HTTP management UI
        - 10673:10673
      environment:
        - SERVICE=statebusrabbitmq
      env_file:
        - ./statebusrabbitmq/.env
      restart: always
      depends_on:
        - rabbitmq


  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=utn"
      - "RABBITMQ_DEFAULT_PASS=iasc"
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672



  vuelos:
    build:
      context: ./vuelos
      args:
        - NODE_ENV=development
    ports:
      - 6000:6000
    environment:
      - SERVICE=vuelos
    env_file:
      - ./vuelos/.env
    depends_on:
      - rabbitmq
    restart: always

  proxy:
    restart: 'always'
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    ports:
      - 80:80
    depends_on:
      - vuelos
#      - aerolineas