apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    app: proxy  # Coincide con la etiqueta utilizada en el Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
