apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerolineas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aerolineas
  template:
    metadata:
      labels:
        app: aerolineas
    spec:
      containers:
        - name: aerolineas
          image: c4849ffa130d9afd239c7e419267ec268d1b1ec94af6c3e01c227e098fb28833
          ports:
            - containerPort: 3015
          env:
            - name: SERVICE
              value: aerolineas
          # Agrega aquí los volúmenes, configuración y recursos necesarios para tu aplicación
---
apiVersion: v1
kind: Service
metadata:
  name: aerolineas
spec:
  selector:
    app: aerolineas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3015
