apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy  # Coincide con la etiqueta utilizada aquí
  template:
    metadata:
      labels:
        app: proxy  # Coincide con la etiqueta utilizada aquí
    spec:
      containers:
        - name: proxy
          image: nginx:latest
          ports:
            - containerPort: 80
          # Aquí puedes agregar la configuración adicional de NGINX si es necesario
