apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerolineas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aerolineas
  template:
    metadata:
      labels:
        app: aerolineas
    spec:
      containers:
        - name: aerolineas
          image: node:20-alpine  # Agrega un espacio y coloca la etiqueta de la imagen (por ejemplo, "node:20-alpine")
          ports:
            - containerPort: 3015
          env:
            - name: SERVICE
              value: aerolineas
          # Agrega aquí los volúmenes, configuración y recursos necesarios para tu aplicación

apiVersion: v1
kind: Service
metadata:
  name: aerolineas
spec:
  selector:
    app: aerolineas
  ports:
    - protocol: TCP
      port: 3015
      targetPort: 3015  # Usa la misma etiqueta de puerto que en "port"
